name = "Corpuscles"
uuid = "e78a0372-c628-4773-9c8d-eb17d149bf93"
authors = ["Johannes Schumann", "Tamas Gal"]
version = "2.3.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAtomic = "a7773ee8-282e-5fa2-be4e-bd808c38a91a"

[compat]
julia = "1"
Unitful = "0.18, 1"
UnitfulAtomic = "0.3.0, 1"
DocStringExtensions = "0.8, 0.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
